/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import controller.TaskController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;



public class App {


    public static void main(String[] args) throws ClassNotFoundException, ParseException {
        
        TaskController controller = new TaskController();
        
        Task task = new Task();
        task.setIdProject(4);
        SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yyyy");
        Date deadline = simpleDate.parse("10/10/2929");
        task.setCompleted(true);
        task.setDescription("teste");
        task.setName("teste");
        task.setNotes("testef");
        task.setId(4);
        task.setDeadline(deadline);
        controller.updade(task);
        
        
        
        /*ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setId(2);
        project.setName("eteva");
        project.setDescription("igira");
        projectController.update(project);
        
        
        List<Project> projects = projectController.getAll();
        System.out.println(projects.size());
*/    
}
}
