/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DeadlineColumn;
import util.TaskTableModel;

/**
 *
 * @author Sheldon
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ProjectController projectController;
    TaskController taskController;
    DefaultListModel projectModel;
    TaskTableModel taskModel;
    public main() throws ClassNotFoundException {
        initComponents();
        initDataController();
        initComponentsModel();
        decorateTaskHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelTasks = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();
        panelTitle = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        subtittle = new javax.swing.JLabel();
        panelProjects = new javax.swing.JPanel();
        textProject = new javax.swing.JLabel();
        projectPlus = new javax.swing.JLabel();
        panelTask = new javax.swing.JPanel();
        textTask = new javax.swing.JLabel();
        taskPlus = new javax.swing.JLabel();
        panelList = new javax.swing.JPanel();
        scrollPanelProjects = new javax.swing.JScrollPane();
        listProjects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        panelEmptyList = new javax.swing.JPanel();
        emptyListIcon = new javax.swing.JLabel();
        empyListTitle = new javax.swing.JLabel();
        emptyListSubtitle = new javax.swing.JLabel();

        jScrollPanelTasks.setBackground(java.awt.Color.white);

        jTableTasks.setAutoCreateRowSorter(true);
        jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableTasks.setGridColor(new java.awt.Color(204, 204, 204));
        jTableTasks.setRowHeight(50);
        jTableTasks.setSelectionBackground(java.awt.Color.white);
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPanelTasks.setViewportView(jTableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setMinimumSize(new java.awt.Dimension(600, 800));

        panelTitle.setBackground(new java.awt.Color(0, 153, 102));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sheldon\\Documents\\NetBeansProjects\\TodoApp\\app\\src\\main\\resources\\tick.png")); // NOI18N
        Title.setText(" Todo App");

        subtittle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subtittle.setForeground(new java.awt.Color(255, 255, 255));
        subtittle.setText("Anote tudo, não esqueça de nada!");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtittle)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelProjects.setBackground(java.awt.Color.white);
        panelProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textProject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textProject.setForeground(new java.awt.Color(0, 153, 102));
        textProject.setText("Projetos");

        projectPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        projectPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectPlusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelProjectsLayout = new javax.swing.GroupLayout(panelProjects);
        panelProjects.setLayout(panelProjectsLayout);
        panelProjectsLayout.setHorizontalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projectPlus)
                .addGap(15, 15, 15))
        );
        panelProjectsLayout.setVerticalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textProject)
                    .addComponent(projectPlus))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelTask.setBackground(java.awt.Color.white);
        panelTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textTask.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textTask.setForeground(new java.awt.Color(0, 153, 102));
        textTask.setText("Tarefas");

        taskPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        taskPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskPlusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTaskLayout = new javax.swing.GroupLayout(panelTask);
        panelTask.setLayout(panelTaskLayout);
        panelTaskLayout.setHorizontalGroup(
            panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taskPlus)
                .addGap(15, 15, 15))
        );
        panelTaskLayout.setVerticalGroup(
            panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTask)
                    .addComponent(taskPlus))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelList.setBackground(java.awt.Color.white);
        panelList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listProjects.setBorder(null);
        listProjects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProjects.setFixedCellHeight(50);
        listProjects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        listProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProjectsMouseClicked(evt);
            }
        });
        scrollPanelProjects.setViewportView(listProjects);

        javax.swing.GroupLayout panelListLayout = new javax.swing.GroupLayout(panelList);
        panelList.setLayout(panelListLayout);
        panelListLayout.setHorizontalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListLayout.setVerticalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelProjects)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        panelEmptyList.setBackground(java.awt.Color.white);

        emptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        empyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        empyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empyListTitle.setText("Nenhuma tarefa por aqui :D");

        emptyListSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emptyListSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        emptyListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyListSubtitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa.");

        javax.swing.GroupLayout panelEmptyListLayout = new javax.swing.GroupLayout(panelEmptyList);
        panelEmptyList.setLayout(panelEmptyListLayout);
        panelEmptyListLayout.setHorizontalGroup(
            panelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyListIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emptyListSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEmptyListLayout.setVerticalGroup(
            panelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmptyListLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(emptyListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emptyListSubtitle)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanel5.add(panelEmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectPlusMouseClicked
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this,rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        projectDialogScreen.addWindowListener(new WindowAdapter(){
        public void windowClosed(WindowEvent e){
            try {
                loadProjects();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_projectPlusMouseClicked

    private void taskPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskPlusMouseClicked
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this,rootPaneCheckingEnabled);
        int projectIndex = listProjects.getSelectedIndex();
        Project project = (Project) projectModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        taskDialogScreen.setVisible(true);
        taskDialogScreen.addWindowListener(new WindowAdapter(){
  
           public void windowClosed(WindowEvent e){
               int projectIndex = listProjects.getSelectedIndex();
               Project project = (Project) projectModel.get(projectIndex);
               try {
                   loadTasks(project.getId());
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
               }
               
           } 
        });
    }//GEN-LAST:event_taskPlusMouseClicked

    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        try {
            int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
            int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
            Task task = taskModel.getTasks().get(rowIndex);
            switch(columnIndex){
                case 4:
                    
                {
                    try {
                        taskController.updade(task);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                case 6:
                    int projectIndex = listProjects.getSelectedIndex();
                    Project project = (Project) projectModel.get(projectIndex);
                {
                    try {
                        taskController.removeById(task.getId());
                    } catch (SQLException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                    taskModel.getTasks().remove(task);
                    loadTasks(project.getId());

                default:
                    break;
                    
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableTasksMouseClicked

    private void listProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProjectsMouseClicked
        int projectIndex = listProjects.getSelectedIndex();
        
        Project project = (Project) projectModel.get(projectIndex);
        try {
            loadTasks(project.getId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel emptyListIcon;
    private javax.swing.JLabel emptyListSubtitle;
    private javax.swing.JLabel empyListTitle;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPanelTasks;
    private javax.swing.JTable jTableTasks;
    private javax.swing.JList<String> listProjects;
    private javax.swing.JPanel panelEmptyList;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelProjects;
    private javax.swing.JPanel panelTask;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JLabel projectPlus;
    private javax.swing.JScrollPane scrollPanelProjects;
    private javax.swing.JLabel subtittle;
    private javax.swing.JLabel taskPlus;
    private javax.swing.JLabel textProject;
    private javax.swing.JLabel textTask;
    // End of variables declaration//GEN-END:variables

    private void decorateTaskHeader() {
        jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTableTasks.getTableHeader().setBackground(new Color(0, 153, 102));
        jTableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableTasks.setAutoCreateRowSorter(true);
        jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumn());
        jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("edit"));
        jTableTasks.getColumnModel().getColumn(6).setCellRenderer(new ButtonColumnCellRenderer("delete"));

    }
    
    private void initDataController(){
        projectController = new ProjectController();
        taskController = new TaskController();
    }
    
    private void initComponentsModel() throws ClassNotFoundException{
        projectModel = new DefaultListModel();
        loadProjects();
        taskModel = new TaskTableModel();
        jTableTasks.setModel(taskModel);
      // loadTasks(project.getId());

       if(!projectModel.isEmpty()){
           listProjects.setSelectedIndex(0);
           Project project = (Project) projectModel.get(0);
           loadTasks(project.getId());
       }

    }
    void loadProjects() throws ClassNotFoundException{
        List<Project> projects = projectController.getAll();
        projectModel.clear();
        
        for(int i=0; i < projects.size(); i++){
            projectModel.addElement(projects.get(i));
            
        }
        listProjects.setModel(projectModel);
    }
    
    
    
    void loadTasks(int id) throws ClassNotFoundException{
        List<Task> tasks = taskController.getAll(id);
        taskModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());
        
    }
    
    
    private void showJTableTasks(boolean hastasks){
        
        if(hastasks){
            if(panelEmptyList.isVisible()){
                panelEmptyList.setVisible(false);
                jPanel5.remove(panelEmptyList);
            }
            jPanel5.add(jScrollPanelTasks);
            jScrollPanelTasks.setVisible(true);
            jScrollPanelTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
            
        }
        else{
            if(jScrollPanelTasks.isVisible()){
                jScrollPanelTasks.setVisible(false);
                jPanel5.remove(jScrollPanelTasks);
                
            }
            jPanel5.add(panelEmptyList);
            panelEmptyList.setVisible(true);
            panelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
    }
}
