/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Sheldon
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    Project project;
      TaskController controller;

    //TaskController controller;

    /**
     * Creates new form TaskDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new TaskController();
        textNameAlert.setVisible(false);
        textDeadlineAlert.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitlte = new javax.swing.JPanel();
        textTitle = new javax.swing.JLabel();
        buttonSave = new javax.swing.JLabel();
        panelContainer = new javax.swing.JPanel();
        textName = new javax.swing.JLabel();
        textDescription = new javax.swing.JLabel();
        textTime = new javax.swing.JLabel();
        textNotes = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        scrollPanelDescription = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        scrollPanelNotes = new javax.swing.JScrollPane();
        textAreaNotes = new javax.swing.JTextArea();
        textFieldTime = new javax.swing.JFormattedTextField();
        textNameAlert = new javax.swing.JLabel();
        textDeadlineAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(400, 500));

        PanelTitlte.setBackground(new java.awt.Color(0, 153, 102));

        textTitle.setBackground(java.awt.Color.white);
        textTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textTitle.setForeground(java.awt.Color.white);
        textTitle.setText("Adicionar tarefas");

        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        buttonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelTitlteLayout = new javax.swing.GroupLayout(PanelTitlte);
        PanelTitlte.setLayout(PanelTitlteLayout);
        PanelTitlteLayout.setHorizontalGroup(
            PanelTitlteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitlteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(buttonSave)
                .addGap(25, 25, 25))
        );
        PanelTitlteLayout.setVerticalGroup(
            PanelTitlteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitlteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelTitlteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitle)
                    .addComponent(buttonSave))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelContainer.setBackground(java.awt.Color.white);

        textName.setText("Nome da tarefa");

        textDescription.setText("Descrição da tarefa");

        textTime.setText("Prazo da tarefa");

        textNotes.setText("Notas");

        textFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNameActionPerformed(evt);
            }
        });

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        scrollPanelDescription.setViewportView(textAreaDescription);

        textAreaNotes.setColumns(20);
        textAreaNotes.setRows(5);
        scrollPanelNotes.setViewportView(textAreaNotes);

        textFieldTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        textFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTimeActionPerformed(evt);
            }
        });

        textNameAlert.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textNameAlert.setForeground(new java.awt.Color(255, 0, 0));
        textNameAlert.setText("* campo obrigatório");

        textDeadlineAlert.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textDeadlineAlert.setForeground(new java.awt.Color(255, 0, 0));
        textDeadlineAlert.setText("* campo obrigatório");

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldTime)
                    .addComponent(textDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNotes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(scrollPanelNotes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContainerLayout.createSequentialGroup()
                        .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNameAlert))
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDeadlineAlert)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        panelContainerLayout.setVerticalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textName)
                    .addComponent(textNameAlert))
                .addGap(5, 5, 5)
                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTime)
                    .addComponent(textDeadlineAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitlte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitlte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNameActionPerformed

    private void textFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTimeActionPerformed

    private void buttonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMouseClicked
       try{
           if(!textFieldName.getText().isEmpty() && !textFieldTime.getText().isEmpty()){
                       Task task = new Task();
        task.setIdProject(project.getId());
        task.setName(textFieldName.getText());
        task.setDescription(textAreaDescription.getText());
        task.setCompleted(false);
        task.setNotes(textAreaNotes.getText());
        
        SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yyyy");
        Date deadline = null;
        deadline = simpleDate.parse(textFieldTime.getText());
        task.setDeadline(deadline);
        controller.save(task);
        JOptionPane.showMessageDialog(panelContainer, "Tarefa salva com sucesso!");
         this.dispose();
           }
           else{
               JOptionPane.showMessageDialog(panelContainer,"Campos obrigatorios não foram preenchidos.");
               textNameAlert.setVisible(true);
               textDeadlineAlert.setVisible(true);
           }

        
       
       } catch(Exception e){
           JOptionPane.showMessageDialog(panelContainer, e.getMessage());
       }
       
      
        
        
    }//GEN-LAST:event_buttonSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTitlte;
    private javax.swing.JLabel buttonSave;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JScrollPane scrollPanelDescription;
    private javax.swing.JScrollPane scrollPanelNotes;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextArea textAreaNotes;
    private javax.swing.JLabel textDeadlineAlert;
    private javax.swing.JLabel textDescription;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JFormattedTextField textFieldTime;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textNameAlert;
    private javax.swing.JLabel textNotes;
    private javax.swing.JLabel textTime;
    private javax.swing.JLabel textTitle;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }

}
